### ISSUE TITLE
"Failed to fetch gasPrice" causes the stack trace in the logs

### ISSUE THREAD

**Issue by akolotov** [zkBob/zeropool-relayer#34]
Consider to gracefully handle error "Failed to fetch gasPrice" and to not flood the logs with the stack trace.

```
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5 #033[33mwarn#033[39m: Failed to fetch gasPrice Error: Returned error: Internal error
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at Object.ErrorResponse (/app/node_modules/web3-core-helpers/lib/errors.js:28:19)
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at /app/node_modules/web3-core-requestmanager/lib/index.js:300:36
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/lib/index.js:98:13)
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at XMLHttpRequest._setReadyState (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at IncomingMessage.<anonymous> (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at IncomingMessage.emit (node:events:525:35)
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at endReadableNT (node:internal/streams/readable:1358:12)
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5   [stack]: 'Error: Returned error: Internal error\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at Object.ErrorResponse (/app/node_modules/web3-core-helpers/lib/errors.js:28:19)\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at /app/node_modules/web3-core-requestmanager/lib/index.js:300:36\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/lib/index.js:98:13)\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at XMLHttpRequest._setReadyState (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at IncomingMessage.<anonymous> (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at IncomingMessage.emit (node:events:525:35)\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at endReadableNT (node:internal/streams/readable:1358:12)\n' +
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5     '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5   [message]: 'Returned error: Internal error',
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5   data: null
Sep 13 13:52:43 relayer-mpv zk-zkbob-relayer-1/6298a67e19a5  }; using default value {"timestamp":"2022-09-13T10:52:43.862Z"}
```

**Comment by LyzeOfKiel** [comment]
Fixed in #96
