### ISSUE TITLE
Remove error stack traces on failed assertions

### ISSUE THREAD

**Issue by LyzeOfKiel** [zkBob/zeropool-relayer#57]
Example:
```
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b  #033[31merror#033[39m: Assertion error: Incorrect transfer proof {"timestamp":"2022-09-15T10:42:08.332Z"}
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b Error: Incorrect transfer proof
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at checkTxProof (/app/zp-relayer/validateTx.js:62:16)
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at /app/zp-relayer/validateTx.js:215:36
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at /app/zp-relayer/validateTx.js:32:27
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at Generator.next (<anonymous>)
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at /app/zp-relayer/validateTx.js:8:71
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at new Promise (<anonymous>)
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at __awaiter (/app/zp-relayer/validateTx.js:4:12)
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at checkAssertion (/app/zp-relayer/validateTx.js:31:12)
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at /app/zp-relayer/validateTx.js:215:15
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at Generator.next (<anonymous>)
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at fulfilled (/app/zp-relayer/validateTx.js:5:58)
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at runMicrotasks (<anonymous>)
Sep 15 03:42:08 relayer-mpv zk-zkbob-relayer-1/3b2ae199da3b     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by LyzeOfKiel** [comment]
Closed in https://github.com/zkBob/zeropool-relayer/pull/69
